# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_deleted_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deleted_Posts',
            new_name='Del_Posts',
        ),
    ]
