# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170313_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Del_Posts',
            new_name='Del_Post',
        ),
    ]
